Fix loading undefined classes, attribute error, key error & optional init
Classes not in the Nowack_Lab mainspace (e.g. those created in jupyter
or those from a different branch) now load using Measurement's default
load function.

When tried on linux with:
Python 3.6.1 (default, Jun 21 2017, 18:48:35)
IPython 6.1.0
I received the errors:

AttributeError: 'dict' object has no attribute '__dict__'
KeyError: 'instruments'

I added try except blocks to maintain functionality and added some
minor fixes.  It seems to load correctly for me.

DisableInits.py was added to prevent nowack_lab init from importing
various packages that are not present on linux and non measurement
machines.